version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres_sequelize_container
    restart: always
    ports:
      - ${POSTGRES_PORTS}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_VOLUMES}